### ISSUE TITLE
Add TAF Tests for App Service V2 endpoints

### ISSUE THREAD

**Issue by lenny-intel** [edgexfoundry/edgex-taf#155]
Add tests for the V2 endpoint covered by theses issues once app-service-configurable has them enabled.
https://github.com/edgexfoundry/app-functions-sdk-go/issues/432
https://github.com/edgexfoundry/app-functions-sdk-go/issues/431
https://github.com/edgexfoundry/app-functions-sdk-go/issues/430
https://github.com/edgexfoundry/app-functions-sdk-go/issues/429
https://github.com/edgexfoundry/app-functions-sdk-go/issues/428
https://github.com/edgexfoundry/app-functions-sdk-go/issues/427

**Comment by lenny-intel** [comment]
Blocked waiting for implementations to be completed.

**Comment by jinlinGuan** [comment]
Reopen for the implementation.
