### ISSUE TITLE
Enhancement: Add helper functions for testing

### ISSUE THREAD

**Issue by jinlinGuan** [edgexfoundry/edgex-taf#19]
This issue is moved from [edgexfoundry/blackbox-testing#252](https://github.com/edgexfoundry/blackbox-testing/issues/252)

**Comment by cloudxxx8** [comment]
in TAF, we have keywords as help functions to verify values
https://github.com/edgexfoundry/edgex-taf/blob/bdb3d20b13764e2bc14b8c8ca2e3677e0b2433c6/TAF/testCaseModules/keywords/common/commonKeywords.robot

close this issue
