### ISSUE TITLE
Core-Data: AddEvent -- Negative Test for Mal-formed Event

### ISSUE THREAD

**Issue by jinlinGuan** [edgexfoundry/edgex-taf#20]
This issue is moved from [edgexfoundry/blackbox-testing#265](https://github.com/edgexfoundry/blackbox-testing/issues/265)

**Comment by cloudxxx8** [comment]
@jinlinGuan have already we made the negative test for core-data V2 API?

**Comment by cloudxxx8** [comment]
we've implemented this in 
https://github.com/edgexfoundry/edgex-taf/blob/bdb3d20b13764e2bc14b8c8ca2e3677e0b2433c6/TAF/testScenarios/functionalTest/V2-API/core-data/event/POST-negative.robot

close this issue
