### ISSUE TITLE
Missing tests for CBOR events

### ISSUE THREAD

**Issue by jinlinGuan** [edgexfoundry/edgex-taf#21]
This issue is moved from [edgexfoundry/blackbox-testing#338](https://github.com/edgexfoundry/blackbox-testing/issues/338)

**Comment by cloudxxx8** [comment]
fixed by https://github.com/edgexfoundry/blackbox-testing/pull/416 and fixed by https://github.com/edgexfoundry/blackbox-testing/pull/415
