### ISSUE TITLE
Integration tests for Store and Forward capability

### ISSUE THREAD

**Issue by lenny-intel** [edgexfoundry/edgex-taf#211]
Add integration tests to cover the Store and Forward capability.

Acceptance Criteria is as follows:

- Data is stored for later retry when export function (HTTP or MQTT) fails and persistOnFailure is true and config setting Writeable.StoreAndForward.Enable = true
- Stored data is exported when retry occurs and connection is good just as if it was exported without error originally.
- Stored data is cleared from the DB once successfully retried.
- Stored data retry count is incremented each time the export retry fails and is updated in DB.
- Stored data is cleared from the DB after the maximum configured retires. (Writeable.StoreAndForward.MaxRetries config setting)
- Changing the function pipeline results in any data stored for that app service to be cleared on the next retry.
- Retry loop is only run when config setting Writeable.StoreAndForward.Enabled is true
- Retry loop interval is set by the Writeable.StoreAndForward.RetryInterval config setting
- Export retries will resume after application service is restarted, i.e. store data is persisted between restarts of the application service.
- RetryCount resumes after application service restart, i.e. it isn't reset.
- Changes to Writeable.StoreAndForward values are dynamically processed without restarting the application service.

**Comment by lenny-intel** [comment]
This can be an extension of the existing End to End testing.

**Comment by cloudxxx8** [comment]
@lenny-intel Cherry is working on writing the related test cases.
However, from the blackbox test point of view, we won't verify or access database directly because there is no API for that.
We will only verify the behavior of app service from the external service.

**Comment by cloudxxx8** [comment]
@lenny-intel could you please clarify this item?
Changing the function pipeline results in any data stored for that app service to be cleared on the next retry.

We tested it manually by changing pipeline function at runtime, but the stored data didn't be cleared.  Is it a bug?
