### ISSUE TITLE
Backward test failure

### ISSUE THREAD

**Issue by cherrycl** [edgexfoundry/edgex-taf#212]
Base on [developer-script PR#330](https://github.com/edgexfoundry/developer-scripts/pull/330), needs to change the used filename from `docker-compose-nexus-base.yml` to `docker-compose-base.yml` when generating backword docker-compose file.

**Comment by lenny-intel** [comment]
Please note that I have another PR that is moving the files to thee `compose-generator` folder. I will submit a TAF PR to update the the new URL once that PR merges.
