### ISSUE TITLE
[SmokeTest] Query all device services returns incorrect number of device services

### ISSUE THREAD

**Issue by jinlinGuan** [edgexfoundry/edgex-taf#226]
@jinlinGuan, @cherrycl , TAF smoke tests failing due to un-related (to PR change) V2 TAF metadata test failing.
https://jenkins.edgexfoundry.org/blue/organizations/jenkins/edgexfoundry%2Fedgex-taf-pipelines/detail/smoke-test/39/tests

Should V2 tests be in the Smoke Tests for Hanoi since they V2 API is still WIP??

_Originally posted by @lenny-intel in https://github.com/edgexfoundry/developer-scripts/issues/341#issuecomment-728140537_

The test variable `${index}` for device service names is set to `${EMPTY}`, so delete device services by names fails, which causes incorrect number of device services when query all device services.

**Comment by cloudxxx8** [comment]
fixed by #227
