### ISSUE TITLE
Kuiper integration test/smoke test

### ISSUE THREAD

**Issue by wendy0211** [edgexfoundry/edgex-taf#231]
Rules are added/removed ok
•Rule that calls back on EdgeX works
•Remove the need for manual tests (automate these – these serve as guide)
•Check what Kuiper team has already

**Comment by cloudxxx8** [comment]
We could only write the test scenario first, and will implement it once Kuiper becomes available with EdgeX V2 API.

**Comment by lenny-intel** [comment]
@cloudxxx8 , @cherrycl , note that the current Kuiper version isn't integrated with V2 DTOs/API. I recommend putting this on hold until we have there 1.20 release scheduled for next week May 26th.

**Comment by lenny-intel** [comment]
@cloudxxx8 , @cherrycl , Kuiper beta release for edgex V2 is now in compose files. Currently only works in non-secure mode.
