### ISSUE TITLE
Verify TAF tests to be put against Snaps

### ISSUE THREAD

**Issue by wendy0211** [edgexfoundry/edgex-taf#232]
• Snap tests need to be migrated
• Might be some tests cases not covered by TAF yet

**Comment by siggiskulason** [comment]
@cloudxxx8 - I am working on getting the TAF tests to run with snaps. Has any work been done on this? What tests were you planning to migrate? This issue could be assigned to me and I can create a PR with the support for TAF testing and snaps once I've finished.

**Comment by cloudxxx8** [comment]
@siggiskulason thanks for taking care of this.  we haven't done anything so far.
