### ISSUE TITLE
Stop Backward Test

### ISSUE THREAD

**Issue by cherrycl** [edgexfoundry/edgex-taf#233]
V2 API is not compatible with V1 API. Stop the backward test, will restart it if later releases need the test.

**Comment by cloudxxx8** [comment]
This issue should be moved to taf-pipeline

**Comment by cherrycl** [comment]
Fixed on [edgex-taf-pipeline PR #45](https://github.com/edgexfoundry/edgex-taf-pipelines/pull/45).
