### ISSUE TITLE
Update the service name to consistent with docker-compose file

### ISSUE THREAD

**Issue by cherrycl** [edgexfoundry/edgex-taf#271]
Both services, Vault-work and edgex-proxy , changed name on [developer-script PR #372](https://github.com/edgexfoundry/developer-scripts/pull/372). TAF scripts also need to update.

**Comment by jim-wang-intel** [comment]
@cherrycl: the asc services of security ones also changed:
- from `appservice-http-export-secrets` to `app-service-http-export-secrets` , and 
- from `appservice-mqtt-export-secrets` to `app-service-http-export-secrets` .
I am not sure that affects the TAF scripts or not but just want to make sure we are on the same page.
Thanks!

**Comment by cherrycl** [comment]
> @cherrycl: the asc services of security ones also changed:
> 
> * from `appservice-http-export-secrets` to `app-service-http-export-secrets` , and
> * from `appservice-mqtt-export-secrets` to `app-service-mqtt-export-secrets` .
>   I am not sure that affects the TAF scripts or not but just want to make sure we are on the same page.
>   Thanks!

@jim-wang-intel Yes. It will affect the TAF scripts. Thanks for the reminder.
