### ISSUE TITLE
[V2] Update app-service secret API tests

### ISSUE THREAD

**Issue by jinlinGuan** [edgexfoundry/edgex-taf#275]
Change api from `/secrets` to `/secret` and property `secrets` to `secretData` based on the change in [app-functions-sdk-go PR#648](https://github.com/edgexfoundry/app-functions-sdk-go/commit/78327a46572e967a5a0e34662e53080e530e38da)

**Comment by cherrycl** [comment]
Fixed by PR #276 and #277.
