### ISSUE TITLE
app-service-blackbox-tests service renamed to app-service-functional-tests

### ISSUE THREAD

**Issue by lenny-intel** [edgexfoundry/edgex-taf#284]
With the renaming of ASC blackbox-tests profile to function-tests profile, the service name in compose file also gets renamed.

All references to app-service-blackbox-tests must change to app-service-functional-tests

All refences to `AppServiceUrl_blackbox` should also be renamed to `AppServiceUrl_functional` 

This is related to the following issues, which have PR staged:
https://github.com/edgexfoundry/app-service-configurable/issues/177
https://github.com/edgexfoundry/developer-scripts/issues/382

**Comment by jinlinGuan** [comment]
closed by #285
