### ISSUE TITLE
Fix core-metadata PATCH V2 API testcases by adding ApiVersion

### ISSUE THREAD

**Issue by jinlinGuan** [edgexfoundry/edgex-taf#302]
from
{"device": {"name": "Test-Device-Locked", "adminState": "UNLOCKED"}, "apiVersion": "v2"}
to
{"device": {"name": "Test-Device-Locked", "adminState": "UNLOCKED", **"apiVersion": "v2"**}, "apiVersion": "v2"}

**Comment by cloudxxx8** [comment]
fixed by #303
