### ISSUE TITLE
[Secure Consul Ph. 2] Modify tests/scripts for testing consul accesses in secure mode

### ISSUE THREAD

**Issue by jim-wang-intel** [edgexfoundry/edgex-taf#352]
For TAF testing consul accessed in secure mode properly, the TAF tests/scripts should be modified to read the Bootstrap ACL Consul token from the configuration file location set by `BootstrapTokenPath = "/tmp/edgex/secrets/consul-acl-token/bootstrap_token.json"` in Consul's environment setting for services to be tested. 

Background:
  In secure mode, the consul-tokens are generated for each service when it calls go-mod-bootstrap by setting `useSecretProvider` to `true` and stored inside the Consul agent server.  With reading and parsing `BootstrapToken` from file location of `BootstrapTokenPath`, it can be used to access Consul.

Once the Consul is running in secure tightened mode, any calls to consul agent server will require a Consul token to access it. 
 Thus, for any TAF testing accesses to Consul will require to do so like the above-mentioned manner.

CC:
@lenny-intel 
@cherrycl 
@cloudxxx8

**Comment by jim-wang-intel** [comment]
Hi @lenny-intel  I don't have the committer permission on this repo, so please arrange it accordingly in Security board. Thanks!

**Comment by jim-wang-intel** [comment]
Hi @lenny-intel  this story seems no longer needed right? If so, we can close it.

**Comment by lenny-intel** [comment]
> Hi @lenny-intel this story seems no longer needed right? If so, we can close it.

No, but it needs to be modified. TAF scripts still need to access Consul, so how are they going the get the Access Token?

**Comment by jim-wang-intel** [comment]
> > Hi @lenny-intel this story seems no longer needed right? If so, we can close it.
> 
> No, but it needs to be modified. TAF scripts still need to access Consul, so how are they going the get the Access Token?

Could we just use Consul's bootstrap ACL token instead of individual token; at least that way can get hold of token from the file? 
If bootstrap is not enough, we probably need some more sophisticated ways to retrieve individual consul tokens from Consul via using bootstrap token in the TAF scripts since we don't have that API at all.

**Comment by lenny-intel** [comment]
> Could we just use Consul's bootstrap ACL token instead of individual token

@jim-wang-intel Yes, if that is on disk and can be used to access Console for any service. Please update issue description with details. THX!

**Comment by jim-wang-intel** [comment]
> > Could we just use Consul's bootstrap ACL token instead of individual token
> 
> @jim-wang-intel Yes, if that is on disk and can be used to access Console for any service. Please update issue description with details. THX!

Updated

**Comment by cherrycl** [comment]
@jim-wang-intel @lenny-intel I would like to confirm will Consul be inaccessible without ACL token in secure mode? Is this issue waiting for some issue or PR to be merged? The TAF scripts can access Consul without ACL token in secure mode so far, is it correct?

**Comment by jim-wang-intel** [comment]
> @jim-wang-intel @lenny-intel I would like to confirm will Consul be inaccessible without ACL token in secure mode? Is this issue waiting for some issue or PR to be merged? The TAF scripts can access Consul without ACL token in secure mode so far, is it correct?

Hi @cherrycl  the short answer is yes.  Once the `default_policy` of Consul config changes to `deny`, without an access token, you cannot get data out of consul at all. So far, I've not turned on that switch yet but it will be sometime next week I guess.   FYI, this is issue that I am currently working on: https://github.com/edgexfoundry/edgex-go/issues/3256  related to that.  So TAF would need to gran that token in order to access Consul in the case it talks to the consul itself in the testing script.
