### ISSUE TITLE
device-virtual startup failed with security enabled

### ISSUE THREAD

**Issue by cherrycl** [edgexfoundry/edgex-taf#372]
device-virtual startup failed with security enabled.

**Comment by lenny-intel** [comment]
@jim-wang-intel FYI

**Comment by cherrycl** [comment]
Raised [edgex-compose issue#64](https://github.com/edgexfoundry/edgex-compose/issues/64) for this error.

**Comment by jim-wang-intel** [comment]
This should be fixed by https://github.com/edgexfoundry/edgex-compose/pull/65
