### ISSUE TITLE
Incorrect reading result order cause TAF can't fetch latest reading

### ISSUE THREAD

**Issue by weichou1229** [edgexfoundry/edgex-taf#44]
* Use **http://localhost:48080/api/v1/reading/device/{name}/limit** instead of the query API to fetch the latest reading

Issue description:
The API **http://localhost:48080/api/v1/reading/name/{name}/device/{name}/limit** can't fetch the latest reading because RedisDB implementation is different to MongoDB.

Issue opened https://github.com/edgexfoundry/edgex-go/issues/2394

**Comment by cloudxxx8** [comment]
If you have confirmed it is the Redis specific issue in Core Data, please open an issue on edgex-go
