### ISSUE TITLE
Test for different QoS

### ISSUE THREAD

**Issue by jpwhitemn** [edgexfoundry/edgex-taf#505]
When we get to testing for different configurations and some services on/off, another feature we need to have as part of our "configuration" testing is running with different quality of service settings for messaging.  By default, we run with QoS set to 0.  Options of 1 and 2 are also possible.  This could impact performance or even be a potential issue based on some testing eKuiper did with this setting (although it looks like it was based on eKuiper's implementation of QoS).

**Comment by cloudxxx8** [comment]
This looks like testing the broker, not our service.
