### ISSUE TITLE
Implement config tests for device-virtual 

### ISSUE THREAD

**Issue by jinlinGuan** [edgexfoundry/edgex-taf#510]
configs:
- MessageQueue.Protocol
- MessageQueue.PublishTopicPrefix
- Device.DataTransform
- Device.UpdateLastConnected
- Device.UseMessageBus

**Comment by cherrycl** [comment]
PR #513 is only implemented the following config.
- Device.DataTransform
- Device.UpdateLastConnected
- Device.UseMessageBus

Opened issue #517 for 
- MessageQueue.Protocol
- MessageQueue.PublishTopicPrefix
