### ISSUE TITLE
Update ASC functional tests to use new `aes256` Encrypt algorithm

### ISSUE THREAD

**Issue by lenny-intel** [edgexfoundry/edgex-taf#541]
The `aes` algorithm has been deprecated and replaced with `aes256` 

The `functional-tests`  profile has been update to specify the  `aes256`  algorithm.

Resulting bytes are as follows:

| initialization vector | ciphertext | signing hash |
| ---------- | ---------- | ---- |
| 16 bytes   | variable bytes | 32 bytes |

**Steps to decrypt:**

1. Base64 decode the response
2. Extract the 16 bytes of Init Vector from the beginning of the data
3. Extract the 32 bytes of the Hash signature from the end of the data
4. Extract the cipher text (remaining bytes in the middle)
5. Perform AES256 decode with the following data/settings
    - Key (first 32 bytes of the 64 byte key used by the encrypt function
    - IV from extracted above
    - 256bits
    - CBC
    - PKCS7
    - cipher text extracted above

**Steps to verify the HASH signature** 

1. Extract the 32 bytes of the Hash signature from the end of the data
2. Run SHA512 hash on the remaining data (IV &  ciphertext) using the the second half of the 64 byte key 
3. Verify extract hash matches calculated hash

**Comment by cherrycl** [comment]
@lenny-intel @AlexCuse  For verifying the HASH signature, I have the following questions.

1. Does the step 2 mean using the second half of the 64 byte key as salt?
2. When doing SAH512 hash online [ [SHA512 hash site](https://www.convertstring.com/Hash/SHA512) ] or using python code always got 64 bytes value, not 32 bytes. Does any calculated required for the 64 bytes hash value?

Thank you.
