### ISSUE TITLE
Hi @JamesKButcher   I seek help regarding EdgeX-TAF for functional and integration testing, can we do the complete testing without involving docker ? please let me know for any suggestions. Thanks in advance.

### ISSUE THREAD

**Issue by dipshirajput** [edgexfoundry/edgex-taf#558]
Hi @JamesKButcher  
I seek help regarding EdgeX-TAF for functional and integration testing, can we do the complete testing without involving docker ?
please do let me know for suggestions.
Thanks in advance.

**Comment by dipshirajput** [comment]
@lenny-intel  please let me know for any suggestions. Thanks in advance.

**Comment by weichou1229** [comment]
You can run the Edgex manually and run the test by the python command.
The test command can refer to https://github.com/edgexfoundry/edgex-taf/blob/main/docs/run-tests-on-local.md#run-v2-api-functional-testing
`python3 -m TUC --exclude Skipped --include v2-api -u functionalTest/V2-API/${ServiceDir} -p default`

**Comment by dipshirajput** [comment]
@weichou1229  thanks for the help.
