### ISSUE TITLE
Hi, while running the test for app-service running with MQTT, do we need to change the robot file config for MQTT ? as I can see the robot files are prepared with {APP_HTTP_EXPORT_PORT}. please let me know for suggestions. Thanks in advance.

### ISSUE THREAD

**Issue by dipshirajput** [edgexfoundry/edgex-taf#559]

**Comment by dipshirajput** [comment]
@lenny-intel @weichou1229 @cloudxxx8 please do let me know for any suggestions. Thanks in advance.

**Comment by dipshirajput** [comment]
@lenny-intel  , I observed that when I was running the application service using consul with mqtt, and tried running the python script for app-service testing, the test failed 100%. I read the robot files(GET.robot, POST.robot, etc), they had only HTTP-EXPORT mentioned , when I changed those to MQTT-EXPORT, the test ran with 50% success rate.

I wanted to confirm about this only that was this alteration required in a scenario where I am running the services using consul with mqtt and then trying to run the test ? 
Please let me know if there are any suggestions. Thanks in advance.

**Comment by lenny-intel** [comment]
@dipshirajput , yes you can run app-service from command line with MQTT as the message bus, but you must change the `Trigger` configuration to use MQTT as the MessageBus. 

The App Template has the configuration for MQTT MessageBus commented out here for your reference:
https://github.com/edgexfoundry/app-functions-sdk-go/blob/main/app-service-template/res/configuration.toml#L114-L137

**Comment by dipshirajput** [comment]
Thanks @lenny-intel .
