### ISSUE TITLE
Error with functional test for core-services ...

### ISSUE THREAD

**Issue by dipshirajput** [edgexfoundry/edgex-taf#570]
Hi @cloudxxx8 ,
I am facing the following type of error  for functional test being done for core-services without docker.
**`NotificationGET010 - Query notifications with time range ................. does not contain 'totalCount'`**
**`SubscriptionGET009 - Query subscriptions with specified label by o.............. does not contain 'totalCount'`**
**`ProfileGET010 - Query device profiles by manufacturer's model and ................does not contain 'totalCount'`**
Please let me know for any suggestions . Thanks in advance.

**Comment by cloudxxx8** [comment]
@dipshirajput you are running the latest test against the old version of EdgeX.
totalCount is the new feature in Jakarta (v2.1) release
Please make sure the test script version matches the running services.

**Comment by dipshirajput** [comment]
@cloudxxx8  ok, thanks a lot for the help.
