### ISSUE TITLE
Query: functionTest->device-test->common->3_device-profile

### ISSUE THREAD

**Issue by rajatkumar-eaton** [edgexfoundry/edgex-taf#581]
I ran below command after test setup locally for "device-virtual":

`python3 -m TUC --exclude Skipped -u functionalTest/device-service -p device-virtual`

After running, getting error in the report:
**"The device profile Virtual-Sample-Profile is not found"**

Got below in response:

`GET Response : url=http://localhost:59881/api/v2/deviceprofile/name/Virtual-Sample-Profile 
 status=404, reason=Not Found 
 headers={'Content-Type': 'application/json', 'X-Correlation-Id': '8d6ba1d8-cfa1-41e3-a284-2927fccbd754', 'Date': 'Wed, 02 Mar 2022 15:09:51 GMT', 'Content-Length': '166'} 
 body={"apiVersion":"v2","message":"fail to query object *models.DeviceProfile, because Virtual-Sample-Profile: md|dp:**name doesn't exist in the database"**,"statusCode":404}`

Now my question is, in which "**database**" tried to find out the device profile name? Do we need add any related supporting test data in form of .json file  under **TAF-> testData** dir by uploading "Upload device profile" in ${WORK_DIR}/TAF/testData/core-metadata/deviceprofile/${file} ??

@cherrycl @cloudxxx8  @beaufrusetta  @michaelestrin  Request you to please guide on this.

**Comment by beaufrusetta** [comment]
@lenny-intel can you possibly help with this or ping someone else that could?

**Comment by cloudxxx8** [comment]
@rajatkumar-eaton database is the RedisDB, and it means you don't have the profile for the test cases you want to run.
The test you are running requires the pre-defined Profiles before starting the device-virtual service.  If you want to run your local virtual device service, you have to feed the test data properly.

**Comment by rajatkumar-eaton** [comment]
thanks @cloudxxx8
I have changed the device name as "Random-Binary-Device" which was the actual imported with service, so working fine now.

**Comment by cloudxxx8** [comment]
It depends on how you start your services
The original script starts the service with the following config, so the device and device profiles are created automatically
https://github.com/edgexfoundry/edgex-taf/tree/main/TAF/config/device-virtual

You need to implement your own set up logic if you would like to run your own deployment logic

**Comment by rajatkumar-eaton** [comment]
@cloudxxx8  I have just started the Edgex default core services provided by them only and then tried to trigger default test, but somehow there is mismatch in predefined profile already deployed and TAF test script.

**Comment by cloudxxx8** [comment]
since device-virtual is set up locally on your own, you can modify the config to remove or change the pre-defined device profile or devices

**Comment by jumpingliu** [comment]
@rajatkumar-eaton So far, do you have further questions regarding this issue? If not, can I close it?
