### ISSUE TITLE
In 7_actuation_commands.robot file, Test case : ErrSET001 fails for device-service testing

### ISSUE THREAD

**Issue by dipshirajput** [edgexfoundry/edgex-taf#586]
Hi @cloudxxx8 @weichou1229 @cherrycl ,
In functional-test for device-service, I can see a contradiction scenario in the file, **`7_actuation_commands.robot`** for the test case **ErrSET001** and the keyword "**DS actuates commands to device/sensor by name**" :

In ErrSET001,
```
When Invoke SET command by device ${device_name} and command ${command} with request body ${reading_name}:${reading_value}
    Then Should return status code "500"
```
    
In keyword "DS actuates commands to device/sensor by name" ,
```
When Invoke SET command by device ${device_name} and command ${command} with request body ${reading_name}:${set_reading_value}
    Then Should return status code "200"
```
    
In both these conditions, the expected response status code are different. and I am getting 200 as the status code response for ErrSET001.
why are we expecting different responses for the same conditions ?
Please let me know for any suggestions. Thanks in advance.

**Comment by cloudxxx8** [comment]
you should test them manually first

**Comment by dipshirajput** [comment]
both of these conditions of invoking SET command are the same, then why different response of status code are expected ? @cloudxxx8

**Comment by cloudxxx8** [comment]
The test case name explains it `ErrSET001 - Test DS actuates commands to device/sensor by name with invalid request body`
The request body is invalid.
What is your testing request body to get 200?

**Comment by jumpingliu** [comment]
@dipshirajput 
There is another similar question in #637. For better understanding and communication, I close this issue and we move to #637 to solve the problem. Thanks.
