### ISSUE TITLE
App service with mqtt export and security enabled can't connect to mqtt broker sometimes

### ISSUE THREAD

**Issue by cherrycl** [edgexfoundry/edgex-taf#591]
Fail case: Export002 - Export events/readings to MQTT Server .
Case fail when security enabled.
Run the case alone, the case is passed. If run after the case Export001 - Export events/readings to HTTP Server, the case failed.

Still investigate.

**Comment by dipshirajput** [comment]
@cherrycl  I am not using security, still the test case: **Export002** fails for me giving the following error,
`No export log found on mqtt subscriber.`

Do we have any way to solve it ? Please let me know for any suggestions. Thanks.

**Comment by cherrycl** [comment]
Open [app-functions-sdk-go #1053](https://github.com/edgexfoundry/app-functions-sdk-go/issues/1053) for integration test error. 
Closed this issue

**Comment by cherrycl** [comment]
@dipshirajput Please check the following things:
1. See the logs of app service with mqtt-export to confirm the service receives event.
2. The [MQTTExport.Parameters](https://github.com/edgexfoundry/app-service-configurable/blob/459b5ab38a90f3d3b0fa6675351f46b767a2eeb2/res/mqtt-export/configuration.toml#L49) are correct for your service.

**Comment by dipshirajput** [comment]
@cherrycl 
1. The app-service with mqtt-export running log doesn't receive any event as I can observe in its log.
2. All parameters are correct only.
still, I am facing the error of ,
`${mqtt_broker_received} == '${EMPTY}'`

**Comment by cherrycl** [comment]
@dipshirajput Please investigate why the app-service didn't receive event. If no event is published to app-service, the mqtt subscriber won't receive any data.

**Comment by dipshirajput** [comment]
@cherrycl  ok thanks for guiding.
