### ISSUE TITLE
Regression test needed for delayed-start service ADR

### ISSUE THREAD

**Issue by bnevis-i** [edgexfoundry/edgex-taf#594]
A regression test is needed to test the delayed-start service ADR.

This test may, for example, set an environment variable to launch a service such as device-virtual in delayed start mode, causing it to request its secret store token at runtime.  TAF would then test as normal.

See https://github.com/edgexfoundry/edgex-go/issues/3773

**Comment by JamesKButcher** [comment]
In Core WG call, agreed that automated test of delayed service start is not essential for Kamakura release. Manual tests sufficient initially

**Comment by cloudxxx8** [comment]
@bnevis-i could you please instruct the approach of how to automate this test?  thanks.

**Comment by bnevis-i** [comment]
> @bnevis-i could you please instruct the approach of how to automate this test? thanks.

1. Pick a service, say device-virtual.
2. Set `SECRETSTORE_RUNTIMETOKENPROVIDER_ENABLED=true` in the environment for the service.
3. When `security-secretstore-setup` completes, remove the file `/tmp/edgex/secrets/device-virtual/secrets-token.json` (replace with the name of the service)  This ensures there is no failsafe method to get a secret store token.
4. Start the service and ensure that it comes up properly.  (Not sure quite how to write this test.)

**Comment by cloudxxx8** [comment]
@cherrycl may we close this issue?
