### ISSUE TITLE
ErrSysMgmtGET001 gives 404 instead of 500 as response for system-agent testing.

### ISSUE THREAD

**Issue by dipshirajput** [edgexfoundry/edgex-taf#639]
Hi @cloudxxx8 , @cherrycl ,

for the below test case, I am getting "404" instead of expected "500". Please let me know for any suggestions if you have. Thanks.
```

ErrSysMgmtGET001 - Query metrics of the given services containing non-existent services
    Set Test Variable  ${default_response_time_threshold}  3500   # normally exceed default 1200ms
    When Query Service Metrics  core-data  non-existent-service  support-notifications
    Then Should Return Status Code "207"
    And Should Retrun 200 and metrics For Existent Services And 500 And metrics=None For Non-Existent Services
    And Should Return Content-Type "application/json"
    And Response Time Should Be Less Than "${default_response_time_threshold}"ms
```

![sys](https://user-images.githubusercontent.com/52161957/164441378-e99e7ed9-af4d-4466-a7a9-08c520b6ccf9.png)

**Comment by cloudxxx8** [comment]
@dipshirajput you have to provide your steps, version, and environment, or we won't be able to answer your questions

**Comment by dipshirajput** [comment]
@cloudxxx8 

**version**- Ireland
**environment**- non-docker, without security
**system**- x86
running the following services manually,
core-data, core-metadata,  core-command, support-notifications, support-scheduler, system-agent, app-rules-engine, device-virtual.

steps:
used the following command to perform system-agent testing.
**python3 -m TUC --exclude Skipped --include v2-api -u functionalTest/V2-API/system-agent-p default**

**Comment by cloudxxx8** [comment]
how did you run the service manually?
please provide the complete steps from a clean OS

**Comment by dipshirajput** [comment]
@cloudxxx8 
yes, I am running the services manually. and then using the following command to execute the test for system-agent.

complete step just comprises of,
1. writing the startup.sh, restart-services.sh, stop-services.sh, shutdown.sh in the /utils/scripts/manual/ diirectory.
2. running the services manually. [core-data, core-command, core-metadata, support-notification, support-scheduler, app-rules-engine, system-agent, device-virtual].
3. executing the following commands in sequence for test execution.
```
    export EDGEX_SECURITY_SECRET_STORE=false
    python3 -m TUC --exclude Skipped --include v2-api -u functionalTest/V2-API/system-agent -p default
```

**Comment by cloudxxx8** [comment]
As your description, there is no way we can recreate your environment.
What is the result when you call the API manually?

**Comment by dipshirajput** [comment]
Hi @cloudxxx8 

I am getting 404 as the response even when tested manually, 
my doubt is that in **test case: ErrSysMgmtGET004** , please notice the following step,

**`And Should Retrun 200 And config For Existent Services And 404 And metrics=None For Non-Existent Services`**

this line in **test case: ErrSysMgmtGET004** expects 404 . 
while in another **test case: ErrSysMgmtGET001** , the same step/line is expecting 500, by any chance is there a scope of correction in **test case: ErrSysMgmtGET001**

`**And Should Retrun 200 and metrics For Existent Services And 500 And metrics=None For Non-Existent Services**`

please let me know for any suggestion. Thank you.
![quer](https://user-images.githubusercontent.com/52161957/165453249-ffaa350a-1090-4104-a146-a170c6493e89.png)

**Comment by cloudxxx8** [comment]
I got 500 from my manual test:
```
    {
        "apiVersion": "v2",
        "message": "exit status 1: Error response from daemon: No such container: non-exe\n: {%!s(float64=0) %!s(int64=0) }",
        "statusCode": 500,
        "serviceName": "non-exe",
        "metrics": null
    }
```
I am running Jakarta release manually.

Again, you have to provide to reproduce steps we can use. We can't run your environment based on the steps your provided.

> 1. writing the startup.sh, restart-services.sh, stop-services.sh, shutdown.sh in the /utils/scripts/manual/ diirectory.
> 2. running the services manually. [core-data, core-command, core-metadata, support-notification, support-scheduler, app-rules-engine, system-agent, device-virtual] using the similar command below,

However, you can modify the test scripts to meet your service change and version.

**Comment by cloudxxx8** [comment]
I suspect your binary version is different from mine.
what branch you pulled and compiled for system management agent?

**Comment by dipshirajput** [comment]
@cloudxxx8 
it is Ireland version I am using.

**Comment by cloudxxx8** [comment]
there is no ireland branch in edgex-go
how do you build the binary?

**Comment by dipshirajput** [comment]
@cloudxxx8 
I actually used 2.0.0 version of edgex-go .
To build the binary, 
I followed the following link where for cloning i specified the version number as 2.0.0,
https://github.com/edgexfoundry/edgex-go/tree/v2.0.0

**Comment by cloudxxx8** [comment]
Jakarta is the LTS release, so we will only maintain this branch.
There might be something wrong in v2.0.0 tag.  You can modify your own script to meet the API in your situation.

**Comment by dipshirajput** [comment]
ok, thank you @cloudxxx8 .

**Comment by jumpingliu** [comment]
@dipshirajput  So far, do you have further concerns about this issue?  If not, can I close it?

**Comment by dipshirajput** [comment]
@jumpingliu  no more queries on this.
please close this issue. Thanks.

**Comment by jumpingliu** [comment]
@dipshirajput Thanks.
