### ISSUE TITLE
ErrSysMgmtPOST001 in system management agent not returning 200 for Existent Services.

### ISSUE THREAD

**Issue by dipshirajput** [edgexfoundry/edgex-taf#656]
Hi @cloudxxx8 , @cherrycl ,

for the following test case, **I am getting 500 as response instead of 200 For Existent Services**,

![res2](https://user-images.githubusercontent.com/52161957/165497012-2e30962e-807e-4e72-a5f5-4ec73dca5c67.png)

Also, I can observe in the below report that it is trying to get a response from links related to docker whereas I am doing it for non-docker environment.
Is there any change I might need to do in order to remove its docker dependency ?

![res1](https://user-images.githubusercontent.com/52161957/165497351-f4650aca-3a00-47fc-b6ba-dae7565ca432.png)

**Note:**
[environment details]
1. non-docker environment
2. manual services running
3. Ireland version

please let me know for any suggestions. Thank you.

**Comment by cloudxxx8** [comment]
This SMA API is designed for controlling services, and the default control mechanism is Docker.
If you are not using docker, this API should not be tested, unless you implement your own executor in SMA.
https://docs.edgexfoundry.org/2.1/microservices/system-management/executor/Ch_SysMgmtExecutor/

The default Docker Executor is just a reference implementation.

**Comment by dipshirajput** [comment]
@cloudxxx8  thank you for the clarity.
Also, as I saw on the below link that SMA is deprecated in Ireland, So, does it play an important role for the TAF being used for any of our application?
https://docs.edgexfoundry.org/2.0/api/management/Ch-APISystemManagement/
please suggest If we should include SMA test or not ? [Ireland version, Non-docker environment]

**Comment by cloudxxx8** [comment]
Yes, it is deprecated.  SMA doesn't play any role in TAF.  It's just a test target.
I am not sure how do you want to use it, so it's your decision to include or exclude the tests.

**Comment by dipshirajput** [comment]
Thank you for the clarification. @cloudxxx8 .

**Comment by jumpingliu** [comment]
@dipshirajput So do you have further questions for this issue? If not, can I close it?

**Comment by dipshirajput** [comment]
@jumpingliu  no more queries on this.
please close the issue. Thank you.

**Comment by jumpingliu** [comment]
@dipshirajput Thanks.
