### ISSUE TITLE
status code 200 instead of 416 for functional tests

### ISSUE THREAD

**Issue by dipshirajput** [edgexfoundry/edgex-taf#658]
@cloudxxx8 , @cherrycl 

I had a doubt regarding the test cases in functional, which has an expected response code of 416 and i get 200 even after deleting redis database as suggested by @cherrycl  https://github.com/edgexfoundry/edgex-taf/issues/627#issuecomment-1103656873 .
The same test case sometimes passes and sometimes fail even after redis database is cleaned. 

**issue already raised  :** https://github.com/edgexfoundry/edgex-taf/issues/627#issuecomment-1103812349

Please let me know why am i getting this inconsistency ? Thanks.

**Comment by cherrycl** [comment]
Did you do manual test for this case? When running automation script, the case may test failure because of garbage data. If you can pass the test by manual, then the api shouldn't have issue. Does that make sense?

**Comment by dipshirajput** [comment]
@cherrycl 
yes I did manual test for this case, sometimes its giving me the following response,

```
{
"apiVersion":"v2",
"message":"fail to query transmissions by offset 1000, 
limit 20 and status FAILED","statusCode":416
}
```

but as i keep refreshing the link, very frequently, I get the below response,

```
{
"apiVersion":"v2",
"statusCode":200,
"transmissions":[]
}
```

Also, while I am executing the test, at that time i am able to get 416 as response sometimes when tested manually otherwise I am getting 200 as response.

**Comment by cherrycl** [comment]
For ErrTransmissionGET001 test, API returns 200 with empty response body, this is a bug and has been fixed by [edgex-go PR #3945](https://github.com/edgexfoundry/edgex-go/pull/3945).

**Comment by dipshirajput** [comment]
@cherrycl  Is it fixed in Ireland version ?

**Comment by cherrycl** [comment]
@dipshirajput No, it won't be fixed in Ireland release.

**Comment by dipshirajput** [comment]
@cherrycl  ok thank you.

**Comment by cherrycl** [comment]
@dipshirajput If you don't have any question for this topic, could I close this issue?

**Comment by dipshirajput** [comment]
@cherrycl  yes sure. I don't have further queries for this..

**Comment by cherrycl** [comment]
@dipshirajput Thanks.
