### ISSUE TITLE
Update the size of kamakura image for performance test

### ISSUE THREAD

**Issue by jumpingliu** [edgexfoundry/edgex-taf#672]
# 🚀 Feature Request

### Relevant Package [**REQUIRED**]

 This feature request is for performance test

### Description [**REQUIRED**]
Update the size of kamakura image

### Describe the solution you'd like
 If you have a solution in mind, please describe it.

### Describe alternatives you've considered
 Have you considered any alternative solutions or workarounds?

**Comment by jumpingliu** [comment]
Fixed by PR #673

**Comment by cherrycl** [comment]
Should update on main branch.
