### ISSUE TITLE
Implement the automation tests for UoM feature

### ISSUE THREAD

**Issue by cloudxxx8** [edgexfoundry/edgex-taf#684]
# 🚀 Feature Request

### Relevant Package [**REQUIRED**]

 This feature request is for core-metadata

### Description [**REQUIRED**]
This is a placeholder for implementing test for
https://docs.edgexfoundry.org/2.2/design/adr/core/0022-UoM/

There will be more details once this ADR is implemented

**Comment by cherrycl** [comment]
#701 Only contains scenarios, the scenarios are not implemented.
