### ISSUE TITLE
Implement automation test for device system event

### ISSUE THREAD

**Issue by cherrycl** [edgexfoundry/edgex-taf#695]
# 🚀 Feature Request

### Relevant Package [**REQUIRED**]

 This feature request is for Core Metadata

### Description [**REQUIRED**]
 
This is a placeholder for implementing test for https://docs.edgexfoundry.org/2.3/design/adr/0024-system-events/
There will be more details once this ADR is implemented.

**Comment by jumpingliu** [comment]
Automated testing of metadata system events is implemented by both redis and mqtt message bus, so reopen the issue for the redis one.
