### ISSUE TITLE
Add hash validation for aes256 encrypt algorithm

### ISSUE THREAD

**Issue by cherrycl** [edgexfoundry/edgex-taf#696]
# 🚀 Feature Request

### Relevant Package [**REQUIRED**]

 This feature request is for app-service

### Description [**REQUIRED**]
 
Do hash data validation for aes256 encrypt algorithm. Please see #541 for more details.

### Describe the solution you'd like
 If you have a solution in mind, please describe it.

### Describe alternatives you've considered
 Have you considered any alternative solutions or workarounds?

**Comment by cloudxxx8** [comment]
fixed by #697
