### ISSUE TITLE
Query in Authorization method "Authorization=Bearer" to "X-Auth-Token" for non-docker mode

### ISSUE THREAD

**Issue by bhavikkothari-eaton** [edgexfoundry/edgex-taf#748]
I am trying to run test suite under manual mode but it is getting failed. here I observed that there is **Authorization=Bearer** method used in header and when I change it to **X-Auth-Token** then tests are getting pass. So as per my observations if we change "Authorization=Bearer" to "X-Auth-Token" tests are getting pass. To get pass whole test suite do I need to make changes in each file or is there any other way to get test suite pass ?

Suggestion are required. Thanks in advance

**Comment by cherrycl** [comment]
@bhavikkothari-eaton I saw you also raised this question on slack. Please follow up this issue on slack. Close this issue.
