### ISSUE TITLE
Stop smoke tests

### ISSUE THREAD

**Issue by cloudxxx8** [edgexfoundry/edgex-taf#769]
# 🚀 Feature Request

### Relevant Package [**REQUIRED**]

 This feature request is for smoke tests

### Description [**REQUIRED**]
In the Core WG meeting on 31-Jan-2023, we decided to stop the smoke test for now, and resume the tests after we have stabilized coded.  We will track the failed test cases through the daily tests before that.

**Comment by cherrycl** [comment]
Fixed.
