### ISSUE TITLE
Resume the smoke test

### ISSUE THREAD

**Issue by cloudxxx8** [edgexfoundry/edgex-taf#770]
# 🚀 Feature Request

### Relevant Package [**REQUIRED**]

 This feature request is for smoke tests

### Description [**REQUIRED**]
The smoke tests should be resumed before the 3.0 release

**Comment by cherrycl** [comment]
Fixed by [edgex-taf-pipeline #125](https://github.com/edgexfoundry/edgex-taf-pipelines/pull/125)
