### ISSUE TITLE
TAF reports do not show in Jenkins in online web report

### ISSUE THREAD

**Issue by bnevis-i** [edgexfoundry/edgex-taf#794]
# 🐞 Bug Report

### Is this a regression?
?

### Description and Minimal Reproduction [**REQUIRED**]
TAF reports do not show in Jenkins

![image](https://user-images.githubusercontent.com/21301128/225086831-abee44db-f56f-4979-8757-cee6fa5a2da8.png)

**Comment by cherrycl** [comment]
This is a limitation for LF Jenkins, please download report to local by `zip` link
![image](https://user-images.githubusercontent.com/41656797/225178392-9e0c0d68-8331-4f15-9d91-da3eb2100812.png)
