### ISSUE TITLE
How to use edgexTAF to test device-rest!

### ISSUE THREAD

**Issue by SavantEVO** [edgexfoundry/edgex-taf#797]
Hi everybody. Currently, I want to use edgexTAF to test the device-rest. So what do I need to do with the file ./TAF/config/configuration.py || Thank you!
Image 1: This is the file configuration.py I've edited. Please, is this true? If not what can I do with the device-rest?  Thank you so much
<img width="1073" alt="image" src="https://user-images.githubusercontent.com/109493900/225802577-431ac8a5-4ae5-49db-8a4b-7446320f4f76.png">
`
import os

# Service for testing
SERVICE_NAME = "device-rest"
PREFIX = "thanhtnt/device-rest-arm64-smic"

SECURITY_SERVICE_NEEDED = os.getenv("SECURITY_SERVICE_NEEDED")
if SECURITY_SERVICE_NEEDED == 'true':
    SERVICE_PORT = "59991/device-rest"
else:
    SERVICE_PORT = 59991

SUPPORTED_DATA_TYPES = [
    #     Boolean
    {"dataType": "BOOL", "commandName": "device-rest", "readingName": "device-rest", "readWrite": "RW"},
    {"dataType": "BOOL", "commandName": "device-rest", "readingName": "device-rest", "readWrite": "R"},
    {"dataType": "BOOL", "commandName": "device-rest", "readingName": "device-rest", "readWrite": "W"},
    #     Float
    {"dataType": "FLOAT32", "commandName": "device-rest", "readingName": "device-rest", "readWrite": "RW"},
    {"dataType": "FLOAT32", "commandName": "device-rest", "readingName": "device-rest", "readWrite": "R"},
    {"dataType": "FLOAT32", "commandName": "device-rest", "readingName": "device-rest", "readWrite": "W"},
    {"dataType": "FLOAT64", "commandName": "device-rest", "readingName": "device-rest", "readWrite": "RW"},
    {"dataType": "FLOAT64", "commandName": "device-rest", "readingName": "device-rest", "readWrite": "R"},
    {"dataType": "FLOAT64", "commandName": "device-rest", "readingName": "device-rest", "readWrite": "W"},
    #     Integer
    {"dataType": "INT8", "commandName": "device-rest", "readingName": "device-rest", "readWrite": "RW"},
    {"dataType": "INT8", "commandName": "device-rest", "readingName": "device-rest", "readWrite": "R"},
    {"dataType": "INT8", "commandName": "device-rest", "readingName": "device-rest", "readWrite": "W"},
    {"dataType": "INT16", "commandName": "device-rest", "readingName": "device-rest", "readWrite": "RW"},
    {"dataType": "INT16", "commandName": "device-rest", "readingName": "device-rest", "readWrite": "R"},
    {"dataType": "INT16", "commandName": "device-rest", "readingName": "device-rest", "readWrite": "W"},
    {"dataType": "INT32", "commandName": "device-rest", "readingName": "device-rest", "readWrite": "RW"},
    {"dataType": "INT32", "commandName": "device-rest", "readingName": "device-rest", "readWrite": "R"},
    {"dataType": "INT32", "commandName": "device-rest", "readingName": "device-rest", "readWrite": "W"},
    {"dataType": "INT64", "commandName": "device-rest", "readingName": "device-rest", "readWrite": "RW"},
    {"dataType": "INT64", "commandName": "device-rest", "readingName": "device-rest", "readWrite": "R"},
    {"dataType": "INT64", "commandName": "device-rest", "readingName": "device-rest", "readWrite": "W"},
    #     Unsigned Integer
    {"dataType": "UINT8", "commandName": "device-rest", "readingName": "device-rest", "readWrite": "RW"},
    {"dataType": "UINT8", "commandName": "device-rest", "readingName": "device-rest", "readWrite": "R"},
    {"dataType": "UINT8", "commandName": "device-rest", "readingName": "device-rest", "readWrite": "W"},
    {"dataType": "UINT16", "commandName": "device-rest", "readingName": "device-rest", "readWrite": "RW"},
    {"dataType": "UINT16", "commandName": "device-rest", "readingName": "device-rest", "readWrite": "R"},
    {"dataType": "UINT16", "commandName": "device-rest", "readingName": "device-rest", "readWrite": "W"},
    {"dataType": "UINT32", "commandName": "device-rest", "readingName": "device-rest", "readWrite": "RW"},
    {"dataType": "UINT32", "commandName": "device-rest", "readingName": "device-rest", "readWrite": "R"},
    {"dataType": "UINT32", "commandName": "device-rest", "readingName": "device-rest", "readWrite": "W"},
    {"dataType": "UINT64", "commandName": "device-rest", "readingName": "device-rest", "readWrite": "RW"},
    {"dataType": "UINT64", "commandName": "device-rest", "readingName": "device-rest", "readWrite": "R"},
    {"dataType": "UINT64", "commandName": "device-rest", "readingName": "device-rest", "readWrite": "W"},
]

`
Image2: This is sample_profile.yml 
<img width="402" alt="image" src="https://user-images.githubusercontent.com/109493900/225804631-4bad4388-5d01-4fb5-b936-55135757136d.png">

apiVersion: "v2"
name: "SMIC-EdgeGateway-Registration-Rest-Device-Profile"
manufacturer: ""
model: ""
labels:
  - "rest"
  - "EdgeGateway"
description: "EdgeGateway device profile"

deviceResources:
  - 
    name: "device-profile"
    isHidden: false
    description: "JSON message"
    properties:
      valueType: "Object"
      readWrite: "RW"
      mediaType: "application/json"
  - 
    name: "device-profile-upload"
    isHidden: false
    description: "JSON message"
    properties:
      valueType: "Object"
      readWrite: "RW"
      mediaType: "application/json"
  - 
    name: "device-provisioning"
    isHidden: false
    description: "JSON message"
    properties:
      valueType: "Object"
      readWrite: "RW"
      mediaType: "application/json"

**Comment by cherrycl** [comment]
@SavantEVO If you want to use the TAF script to test device-rest, the naming rule of `profile name / resource name / command name` should be the same as device-virtual and device-modbus that has been developed. For example, profile name set to `REST-Sample-Profile`, resource name set to `REST_DeviceValue_INT64_R`. The `REST` is the `PREFIX` which set to configuration.py. Of course you can set any PREFIX you like, but it should be the same as name in sample_profile.yaml file. 

Below is compare list for parameters of SUPPORTED_DATA_TYPES in configuration.py and sample-profile.yml

| configuration.py | sample-profile.yml |
| --- | --- |
| dataType | value Type |
| commandName | `name` under deviceCommands |
| readingName | `name` under deviceResources |

You can define all supported data type in the device profile, or only part of them you want to test. Please reference the document for current device-rest supported data type [here](https://github.com/edgexfoundry/device-rest-go#commands-1)

**Comment by SavantEVO** [comment]
Thank you so much!

Vào 16:20, Th 6, 17 thg 3, 2023 Cherry Wang ***@***.***> đã
viết:
