### ISSUE TITLE
Problem with test function device-virtual !

### ISSUE THREAD

**Issue by MILANOFCOFEE** [edgexfoundry/edgex-taf#804]
I using the repo https://github.com/edgexfoundry/edgex-taf to test the function device-virtual but I got a problem
- I checked docker ps and device-virtual is up.
<img width="977" alt="image" src="https://user-images.githubusercontent.com/128799769/227493909-567f8d81-36c9-4686-8eb1-ecdb4bf95281.png">
Then, I prepare an environment to test:

>     export WORK_DIR=${HOME}/edgex-taf
>     ${ARCH}: x86_64
>     ${SECURITY_SERVICE_NEEDED}: false
>     ${TEST_STRATEGY}: functional-test
>     ${TEST_SERVICE}: device-virtual
>     ${DEPLOY_SERVICES}: no-deployment
>     cd ${WORK_DIR}/TAF/utils/scripts/docker
>     =>sh run-tests.sh x86_64 false functional-test device-virtual no-deployment

The result shows this image
<img width="1237" alt="image" src="https://user-images.githubusercontent.com/128799769/227504554-475376c7-32fd-4bb6-9b42-9940b2fd2677.png">

[report.log](https://github.com/edgexfoundry/edgex-taf/files/11061369/report.log)
Thank you !!

**Comment by cherrycl** [comment]
Would you please provide all your steps of deployment and run tests?

**Comment by MILANOFCOFEE** [comment]
I tried to run [docker-compose-no-secty.yml] (https://github.com/edgexfoundry/edgex-compose/blob/main/docker-compose-no-secty.yml). deployment: Ubuntu x86_64  
Then I tried to run edgex-taf to test device-virtual with set up the environment
export WORK_DIR=${HOME}/edgex-taf
${ARCH}: x86_64
${SECURITY_SERVICE_NEEDED}: false
${TEST_STRATEGY}: functional-test
${TEST_SERVICE}: device-virtual
${DEPLOY_SERVICES}: no-deployment
cd ${WORK_DIR}/TAF/utils/scripts/docker
Use this command to run test device-virtual 
=>sh run-tests.sh x86_64 false functional-test device-virtual no-deployment
And then I got the result 
<img width="1267" alt="image" src="https://user-images.githubusercontent.com/128799769/227746333-e9a35c01-69d8-4072-94fd-901319762a76.png">

My objective is to learn about edgexTAF. I then decided to try out the virtual device. But I am facing the issue depicted above.

**Comment by cloudxxx8** [comment]
@MILANOFCOFEE the main branch is under development, and the code and result keeps changing everyday.
Please run with the release tag or branch instead, like v2.3.0 tag or levski branch

**Comment by cloudxxx8** [comment]
I saw your images are 2.1.1, so the taf test script should use the jakarta branch

**Comment by MILANOFCOFEE** [comment]
@cloudxxx8 I tried to taf with branch Jakarta but still got a problem.
<img width="1238" alt="image" src="https://user-images.githubusercontent.com/128799769/227769165-a936e019-51c5-4074-a209-fe22da3fc8c4.png">

**Comment by cherrycl** [comment]
@MILANOFCOFEE Please following [this section](https://github.com/edgexfoundry/edgex-taf/blob/jakarta/docs/run-tests-on-local.md#use-python-to-run-tests) to deploy EdgeX. To execute `get-compose-file.sh` to get the custom compose file is required when running TAF tests. There are some specified configurations for the test script.
