### ISSUE TITLE
Problem with test app-service

### ISSUE THREAD

**Issue by MILANOFCOFEE** [edgexfoundry/edgex-taf#810]
I use docker-compose.yml of Jarkarta branch to deploy with App Service testing purposes but when deploying I have problems like below
> Creating edgex-device-modbus  ... error/device-virtual:.:z': invalid mount config for type "bind": invalid mount path: '.' mount path must be absolute
> ERROR: for edgex-device-modbus  Cannot create container for service device-modbus: invalid volume specification: '/TAF/config/device-modbus:.:z': invalid mount config for type "bind": invalid mount path: '.' mount path must be absolute
> ERROR: for device-virtual  Cannot create container for service device-virtual: invalid volume specification: '/TAF/config/device-virtual:.:z': invalid mount config for type "bind": invalid mount path: '.' mount path must be absolute
> ERROR: for device-modbus  Cannot create container for service device-modbus: invalid volume specification: '/TAF/config/device-modbus:.:z': invalid mount config for type "bind": invalid mount path: '.' mount path must be absolute
> ERROR: Encountered errors while bringing up the project.
volume in file docker-compose.yml
<img width="677" alt="image" src="https://user-images.githubusercontent.com/128799769/228445189-ed9909ad-2967-468d-876f-255709d878f5.png">
I tried
> export WORK_DIR=${HOME}/edgex-taf

but not fix the Error
This link I follow 

> https://github.com/edgexfoundry/edgex-taf/blob/jakarta/docs/run-tests-on-local.md#use-python-to-run-tests

**Comment by cherrycl** [comment]
Please follow the next section https://github.com/edgexfoundry/edgex-taf/blob/jakarta/docs/run-tests-on-local.md#run-tests to deploy and run tests.

**Comment by cherrycl** [comment]
Did you do [setup required library](https://github.com/edgexfoundry/edgex-taf/blob/jakarta/docs/run-tests-on-local.md#setup-required-library)?

**Comment by MILANOFCOFEE** [comment]
> Did you do [setup required library](https://github.com/edgexfoundry/edgex-taf/blob/jakarta/docs/run-tests-on-local.md#setup-required-library)?
Yes, I installed it. but still, get the problem
> TypeError: 'module' object is not callable
<img width="866" alt="image" src="https://user-images.githubusercontent.com/128799769/228717643-cbe10728-a229-45e4-9946-5f199ee31838.png">
I did it step by step.

**Comment by cherrycl** [comment]
It seems you lost required module. I tried to step by step to follow the document again, and can't reproduce your issue.

**Comment by MILANOFCOFEE** [comment]
Thank you! I will try again.
