### ISSUE TITLE
All testcases are failed when test with app-service  

### ISSUE THREAD

**Issue by kimanh1** [edgexfoundry/edgex-taf#811]
Now, I'm testing for app-service with functional-testing.
I run in terminal: sh run-tests.sh x86_64 false functional-test app-service no-deployment
But, all testcases are failed.
![image](https://user-images.githubusercontent.com/88702997/228453960-28b9413c-1c1c-43c9-9473-b738e786e2c9.png)
And on the termial show: ConnectionError: HTTPConnectionPool(host='localhost', port=59705): Max retries exceeded with url: /api/v2/ping (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f3878ab4160>: Failed to establish a new connection: [Errno 111] Connection refused')).
![image](https://user-images.githubusercontent.com/88702997/228454480-2a565509-ecbc-4059-994a-9603dd2624ca.png)

Please give me some advice to fix this problem.

**Comment by cherrycl** [comment]
Please provide all your steps of deployment and run tests.

**Comment by kimanh1** [comment]
@cherrycl I clone the edgex-taf jakarta branch of project from EdgeX Foundry  and run commands on terminal:
cd ${HOME}
git clone https://github.com/edgexfoundry/edgex-taf.git
export WORK_DIR=${HOME}/edgex-taf
cd ${WORK_DIR}/TAF/utils/scripts/docker
sh run-tests.sh x86_64 false functional-test app-service no-deployment

**Comment by cherrycl** [comment]
I still can't figure out how you to deploy the EdgeX, the document provide 2 ways to deploy and run tests? You executed the run-test.sh with no-deployment, then how you to deploy EdgeX? By Python command? Could you step by step write down your deployment. 

On the below comment, there is no deployment step.
> @cherrycl I clone the edgex-taf jakarta branch of project from EdgeX Foundry and run commands on terminal: cd ${HOME} git clone https://github.com/edgexfoundry/edgex-taf.git export WORK_DIR=${HOME}/edgex-taf cd ${WORK_DIR}/TAF/utils/scripts/docker sh run-tests.sh x86_64 false functional-test app-service no-deployment

**Comment by kimanh1** [comment]
@cherrycl I use a Docker container to deploy egdex and run tests and all steps follow your document, so I don't know what you really want to know?

**Comment by cherrycl** [comment]
If you deployed EdgeX with TAF Jakarta branch, the services should not contain app-sample. It seems like you get the compose file [here](https://github.com/edgexfoundry/edgex-compose/blob/jakarta/docker-compose-with-app-sample.yml). This compose can't be used on TAF tests. Please remove all this services and execute command `sh run-tests.sh x86_64 false functional-test app-service`, it contains deployment.

**Comment by kimanh1** [comment]
@cherrycl Thank you
