### ISSUE TITLE
Support running test functions with robots. Functional Test Core Metadata !

### ISSUE THREAD

**Issue by MILANOFCOFEE** [edgexfoundry/edgex-taf#819]
Hello everyone, please let me know!
I saw indirect functional to test core-metadata and I saw the file POST, GET, Delete,... So I don't know the flow run of the test with the file robot precisely. Will the robot files run in the sorted order?
https://github.com/edgexfoundry/edgex-taf/tree/main/TAF/testScenarios/functionalTest/V2-API/core-metadata/deviceprofile
<img width="1248" alt="image" src="https://user-images.githubusercontent.com/128799769/230701556-01a9a265-0f27-4652-8c8f-b3d4d314a864.png">

**Comment by cherrycl** [comment]
As my experience, RobotFramework will run the robot files by letter sorting.
