### ISSUE TITLE
Support custom file global_variables.py

### ISSUE THREAD

**Issue by MILANOFCOFEE** [edgexfoundry/edgex-taf#828]
Hello, everybody. I need help with how to custom
BASE_URL = "localhost"
jwt_token = ''
I custom auto-get URL with [library netifaces|import netifaces"] to get IP my local and [import subprocess using file bash.sh]| to get jwt_token. But when I ran the test I got a problem No Module Netiface. I installed netifaces but it did not solve the problem. 
https://github.com/edgexfoundry/edgex-taf/blob/main/TAF/config/global_variables.py
Thank you so much !

**Comment by cherrycl** [comment]
If the token is fixed, you can just put the token [here](https://github.com/edgexfoundry/edgex-taf/blob/353c5963fc72027d90610dcd3add1b9031c78cf2/TAF/config/global_variables.py#L25), and comment out the` Get Token` and `Remove Token` keyword on every suite. 
If the token is only generated before running suite, you can implement your script to replace api-gateway-token.sh with same file name. The file will be executed by `Get Token` and `Remove Token` keyword.
