### ISSUE TITLE
Support  Test app-service.

### ISSUE THREAD

**Issue by MILANOFCOFEE** [edgexfoundry/edgex-taf#834]
Hello everyone, I got a problem when testing app-service. I built an app-service custom. This app-service with behavior GET all core-metadata (local) then POST to Cloud. So can I check the behavior of this app-service? Please give me advice, thank you so much!

**Comment by cherrycl** [comment]
I don't understand what you want to do. If the question is not related TAF tests, could you raise the question on [Discussions](https://github.com/orgs/edgexfoundry/discussions) page.

**Comment by MILANOFCOFEE** [comment]
Thank you @cherrycl
