### ISSUE TITLE
Process integrationTest problem !

### ISSUE THREAD

**Issue by SavantEVO** [edgexfoundry/edgex-taf#837]
Hello everybody, I had a problem when I ran the integration-test. I tried to follow this document to run the demo test branch Jakarta. https://github.com/edgexfoundry/edgex-taf/blob/jakarta/docs/run-tests-on-local.md
When run with this command
`python3 -m TUC --exclude Skipped -u integrationTest -p device-virtual`
Got a consul show below this.
<img width="1037" alt="image" src="https://user-images.githubusercontent.com/109493900/234500585-c6a96a3c-274e-4192-b749-cd19c52ed11d.png">
So what happened I don't know what I made a mistake.
Thank you!

**Comment by cherrycl** [comment]
Would you please provide steps how you setup environment like install libraries and deploy EdgeX?

**Comment by SavantEVO** [comment]
@cherrycl 
I run with the command to deploy edgex with branch Jakarta and then I am using the command `docker ps` I saw service edgex all UP.
I run this command to run file sh get compose from jarkata
`sh get-compose-file.sh x86_64 - jakarta functional-test`

 # Export the following environment variables.

> export WORK_DIR=${HOME}/edgex-taf
> export SECURITY_SERVICE_NEEDED=false
> export COMPOSE_IMAGE=nexus3.edgexfoundry.org:10003/edgex-devops/edgex-compose:latest

`cd ${HOME}/edgex-taf`
`python3 -m TUC --exclude Skipped --include deploy-base-service -u deploy.robot -p default`
Then I run "Run Integration testing" : `python3 -m TUC --exclude Skipped -u integrationTest -p device-virtual` .

**Comment by cherrycl** [comment]
@SavantEVO You ran get-compose-file.sh with `functional-test` but run tests with `integration-test`. Please make both synchronize and run tests again. 
If you still got same failure, for debug, please shows `docker ps -a` and `docker logs edgex-app-external-mqtt-trigger`. 

BTW, just confirm did you got all tests for integration-test failure or only the case failure you captured?

**Comment by MILANOFCOFEE** [comment]
So I run again with all the steps shown below. get compose file with argument 

> sh get-compose-file.sh x86_64 - jakarta integration-test

Then I use this comment to deploy docker-compose

> export WORK_DIR=${HOME}/edgex-taf
> export SECURITY_SERVICE_NEEDED=false
> export COMPOSE_IMAGE=nexus3.edgexfoundry.org:10003/edgex-devops/edgex-compose:latest
> cd${HOME}/edgex-taf
> python3 -m TUC --exclude Skipped --include deploy-base-service -u deploy.robot -p default

I check the status: All with status UP
> docker ps -a

Then I checked the docker logs:

> docker logs edgex-app-external-mqtt-trigger

<img width="1240" alt="image" src="https://user-images.githubusercontent.com/128799769/234758067-e9e10b7f-2f93-4be9-9b4f-8b4e55aeba15.png">

Then I started to run the test:
<img width="860" alt="image" src="https://user-images.githubusercontent.com/128799769/234760784-71b294b6-030c-4cff-a40c-d99c309fb835.png">
This link shows all results after running the test:
https://drive.google.com/file/d/1NpnkcwkHIuPymwufzO5oh4paXMSNeVBs/view?usp=share_link

I check again docker ps -a some app-service exited.
<img width="1214" alt="image" src="https://user-images.githubusercontent.com/128799769/234762181-e0dc0a59-432d-4376-8258-8ec2b3f05246.png">

I check logs this is shown below| 

> msg="Disconnecting from the message bus"

<img width="1237" alt="image" src="https://user-images.githubusercontent.com/128799769/234762342-d8efe8d1-c00c-4131-996d-b131f7b329d0.png">

**Comment by SavantEVO** [comment]
So I run again with all the steps shown below. get compose file with argument 

> sh get-compose-file.sh x86_64 - jakarta integration-test

Then I use this comment to deploy docker-compose

> export WORK_DIR=${HOME}/edgex-taf
> export SECURITY_SERVICE_NEEDED=false
> export COMPOSE_IMAGE=nexus3.edgexfoundry.org:10003/edgex-devops/edgex-compose:latest
> cd${HOME}/edgex-taf
> python3 -m TUC --exclude Skipped --include deploy-base-service -u deploy.robot -p default

I check the status: All with status UP
> docker ps -a

Then I checked the docker logs:

> docker logs edgex-app-external-mqtt-trigger

<img width="1240" alt="image" src="https://user-images.githubusercontent.com/128799769/234758067-e9e10b7f-2f93-4be9-9b4f-8b4e55aeba15.png">

Then I started to run the test:
<img width="860" alt="image" src="https://user-images.githubusercontent.com/128799769/234760784-71b294b6-030c-4cff-a40c-d99c309fb835.png">
This link shows all results after running the test:
https://drive.google.com/file/d/1NpnkcwkHIuPymwufzO5oh4paXMSNeVBs/view?usp=share_link

I check again docker ps -a some app-service exited.
<img width="1214" alt="image" src="https://user-images.githubusercontent.com/128799769/234762181-e0dc0a59-432d-4376-8258-8ec2b3f05246.png">

I check logs this is shown below| 

> msg="Disconnecting from the message bus"

<img width="1237" alt="image" src="https://user-images.githubusercontent.com/128799769/234762342-d8efe8d1-c00c-4131-996d-b131f7b329d0.png">
Please take a look! Thank you so much

**Comment by cherrycl** [comment]
@SavantEVO Please do the following steps to debug the issue.
1. Subscribe MQTT topics `external-request` and `edgex-export` locally. Example. `mosquitto_sub -h localhost -p 1883 -t external-request`. To confirm the event is exported from app-external-mqtt-trigger to mqtt-broker.
2. Run test with command `python3 -m TUC --exclude Skipped -u integrationTest/UC_app_service_configurable -p device-virtual` . This will only run the test `ExternalTrigger001`

**Comment by MILANOFCOFEE** [comment]
@cherrycl
I follow the steps. When I run, there are still some things wrong.
Step 1: I ran: mosquitto_sub -h localhost -p 1883 -t external-request
Maybe nothing event. when subscribe.
<img width="617" alt="image" src="https://user-images.githubusercontent.com/128799769/236983306-3ae2f0bd-ff37-49cf-913c-283e71f58b51.png">

> Keyword 'File Should Not Be Empty' failed after retrying 6 times. The last error was: File '/home/aroma/edgex-taf/TAF/testArtifacts/logs/external-request.log' is empty.

<img width="1029" alt="image" src="https://user-images.githubusercontent.com/128799769/236982639-f3df63ab-4399-4e05-9dc3-fb6481ec00ef.png">

I check logs in the docker |  app-mqtt-export
<img width="1235" alt="image" src="https://user-images.githubusercontent.com/128799769/236984320-0fcf6bc8-aebd-4492-b1a8-669eb603b1fb.png">

**Comment by SavantEVO** [comment]
@cherrycl
I follow the steps. When I run, there are still some things wrong.
Step 1: I ran: mosquitto_sub -h localhost -p 1883 -t external-request
Maybe nothing event. when subscribe.
<img width="617" alt="image" src="https://user-images.githubusercontent.com/128799769/236983306-3ae2f0bd-ff37-49cf-913c-283e71f58b51.png">

> Keyword 'File Should Not Be Empty' failed after retrying 6 times. The last error was: File '/home/aroma/edgex-taf/TAF/testArtifacts/logs/external-request.log' is empty.

<img width="1029" alt="image" src="https://user-images.githubusercontent.com/128799769/236982639-f3df63ab-4399-4e05-9dc3-fb6481ec00ef.png">

I check logs in the docker |  app-mqtt-export
<img width="1235" alt="image" src="https://user-images.githubusercontent.com/128799769/236984320-0fcf6bc8-aebd-4492-b1a8-669eb603b1fb.png">

**Comment by cherrycl** [comment]
Not sure why your app-service can't connect to mqtt-broker. Try to update the `MQTT_BROKER_IP` [here](https://github.com/edgexfoundry/edgex-taf/blob/369bbe668f46a1d7a7ae7217e6f4edc4633d9912/TAF/utils/scripts/docker/common-taf.env#L5) from `172.17.0.1` to `edgex-mqtt-broker` to see the issue still exists or not.

**Comment by SavantEVO** [comment]
Thank you so much ! @cherrycl Maybe I solved the problem about ${ARCH}: x86_64 | arm 64. When handling ${x86_64}
python3 -m TUC --exclude omitted -u integrationTest/UC_app_service_configurable -p device-virtual.
Need to add python -> python3 in the file 
<img width="865" alt="image" src="https://github.com/edgexfoundry/edgex-taf/assets/109493900/ad425ca3-2ca7-496d-8a21-4ef74453acd1">
It runs for me
<img width="860" alt="image" src="https://github.com/edgexfoundry/edgex-taf/assets/109493900/6b6f5cbf-6a94-45e0-b5e6-7b398e617cc7">
