### ISSUE TITLE
Support the Infor test process.

### ISSUE THREAD

**Issue by SavantEVO** [edgexfoundry/edgex-taf#842]
Hello everybody! I have a problem that I need help with. When performing application service information checks about ping, version, configuration, etc. Application service must register through edgex-consul before swagger app-service https://app.swaggerhub.com/apis-docs/EdgeXFoundry1/app-functions-sdk/2.3.0#/default/get_versioncan be used to perform information checking. I want to know if the flow is like that or not?
<img width="871" alt="image" src="https://github.com/edgexfoundry/edgex-taf/assets/109493900/781fc813-2e86-4e4c-8ef0-2734dbd70305">

Thank you!

**Comment by cherrycl** [comment]
@cloudxxx8 Could you help this?

**Comment by cloudxxx8** [comment]
No, Consul is not necessary for executing ping, version, and config API in App Service.

**Comment by cloudxxx8** [comment]
device service and app service are totally different services

**Comment by cloudxxx8** [comment]
yes, they are the default API
if you build an app-service based on app-functions-sdk, ping, version, metric, config APIs will be available automatically.

**Comment by SavantEVO** [comment]
@cloudxxx8 
I have another problem that I need to know more about device service. Any built device service will have bindings to the core metadata. When a device service is built, it needs to register the device-profile in the core metadata. Please tell me more about this!
I found the device service description document in the following link
https://nexus.edgexfoundry.org/content/sites/docs/staging/california/docs/_build/html/Ch-DeviceServices.html
<img width="953" alt="image" src="https://github.com/edgexfoundry/edgex-taf/assets/109493900/6bcff7d1-211f-4ac8-aed0-d84bcc96747c">
I run docker and then check UI about the device-virtual. It has register device-profile
<img width="1268" alt="image" src="https://github.com/edgexfoundry/edgex-taf/assets/109493900/e5acd8bc-fa00-447f-ac45-98ec74ca38ee">

**Comment by cloudxxx8** [comment]
it's not a taf specific question.
please move your question to the project discussion for more support
https://github.com/orgs/edgexfoundry/discussions
