### ISSUE TITLE
Update the size of Minnesota image for performance test

### ISSUE THREAD

**Issue by jumpingliu** [edgexfoundry/edgex-taf#855]
# 🚀 Feature Request

### Relevant Package [**REQUIRED**]

 This feature request is for performance test

### Description [**REQUIRED**]
Update the size of Minnesota image

### Describe the solution you'd like
 If you have a solution in mind, please describe it.

### Describe alternatives you've considered
 Have you considered any alternative solutions or workarounds?

**Comment by cherrycl** [comment]
The image/binary size is updated on [#854](https://github.com/edgexfoundry/edgex-taf/pull/854)

**Comment by cloudxxx8** [comment]
fixed by #854
