### ISSUE TITLE
can we build our images for taf_common and compose to run it on riscv machine

### ISSUE THREAD

**Issue by divyashree123456** [edgexfoundry/edgex-taf#860]
Hi All,
As we have developed our own images for edgex services for riscv machine,now thinking to build a required setup for Edgex-TAF framework on RISCV machine using docker.Is there any Dockerfile available for these two Images used while running TAF.

TAF_COMMON_IMAGE=nexus3.edgexfoundry.org:10003/edgex-taf-common${USE_ARM64}:latest
COMPOSE_IMAGE=nexus3.edgexfoundry.org:10003/edgex-devops/edgex-compose${USE_ARM64}:latest

If not,please let me know how can i create these Images for Riscv.

Thanks in advance

**Comment by cloudxxx8** [comment]
duplicated to https://github.com/orgs/edgexfoundry/discussions/135
