### ISSUE TITLE
Error when get token

### ISSUE THREAD

**Issue by MILANOFCOFEE** [edgexfoundry/edgex-taf#865]
I tried running it but it shows the log as below. I want to know what happens with this error. Could this be from the docker container I develop or something? Please give me advice ? Thank you !
![Screenshot from 2023-08-09 17-05-54](https://github.com/edgexfoundry/edgex-taf/assets/128799769/fc4540ca-b915-463b-9952-5bb3edce3289)

**Comment by cloudxxx8** [comment]
You have to states what you are running and which version you are using.  Winthout any context, we can't help you.
