### ISSUE TITLE
[Performance test] Binary size grow over the threashold

### ISSUE THREAD

**Issue by jumpingliu** [edgexfoundry/edgex-taf#906]
# 🐞 Bug Report

### Affected Services [**REQUIRED**]

 The issue is located in performance test, the container binary size grows over the threashold among all the platforms (machine arm64 and x86)

### Report
Please see the attached test report and metrics.
![image](https://github.com/user-attachments/assets/0d2587a9-926e-4c4f-9ab4-a40eec232a7a)

The normal one:
![Screenshot 2024-08-12 163815](https://github.com/user-attachments/assets/0bc22822-a6ae-4c25-8631-a6e84d3b94c4)

The abnormal one:
![Screenshot 2024-08-12 163521](https://github.com/user-attachments/assets/72260f94-5a30-4687-8a9f-fe7619f23c9d)

**Comment by cherrycl** [comment]
Current binary size of services has been decreased and fit the threshold setting.
![image](https://github.com/user-attachments/assets/d9cfd1d0-6afa-4c5b-a110-1e73ab3a0131)

**Comment by cherrycl** [comment]
On the report of 2024-10-15, some services of binary size are still over threshold setting, will change the threshold based on the size.
![image](https://github.com/user-attachments/assets/2e2aa22c-413c-4c33-a7ae-81e272908612)
